### ISSUE TITLE
Module breaks when disabling Magento_Csp

### ISSUE THREAD

**Issue by jorgb90** [pricemotion/magento2#6]
We just decided to disable Magento_Csp and found out that for us the only module which breaks is this one. It happens when opening a product in the admin. Its because of dependencies in Pricemotion/Magento2/Block/Adminhtml/Catalog/Product/Widget.php. We just removed the lines to get it working for us.

**Comment by jorgb90** [comment]
Please implement this, so that after each composer update the module doesn't break.

**Comment by apeschar** [comment]
Thanks for your report. This has been fixed and will be resolved with the next update.
